server:
  port: 8082
  servlet:
    context-path: /Demo
#@Value使用    
cupSize: B
age: 18
content: "cupSize: ${cupSize}, age: ${age}"
#@ConfigurationProperties(prefix = "gril")使用
gril: 
  cupSize: F
  age: 21