spring: 
  profiles:
    active: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##zhouwq
    password: oracle
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
     